baseURL = "https://max.me.uk/"
disqusShortname = "max-me-uk"
languageCode = "en-gb"
title = "Maximilian Mitchell"
[outputs]
home = ["HTML", "RSS", "JSON"]
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
