version: "3.8"
services:
  admin:
    image: ponzu/ponzu:latest
    volumes:
      - ./admin:/go/src/project
    ports:
      - "8080:8080"

  web:
    build: .
    volumes:
      - ./web/public:/public
    links:
      - admin
    ports:
      - "3000:8080"