version: '3.2'
services:
  web:
    image: maxisme/max.me.uk:latest
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.maxmeuk.rule=Host(`max.me.uk`)"
        - "traefik.http.services.maxmeuk.loadbalancer.server.port=8080"
        - "traefik.http.routers.maxmeuk.middlewares=404"
    networks:
      - traefik

networks:
  traefik:
    external: true